-Add flags for installing init.d script/systemd service -Add signal handlers -Fixed inconsistencies with low charge power off threshold

diff --git a/extra/S46sw6106mon b/extra/S46sw6106mon
--- a/extra/S46sw6106mon
+++ b/extra/S46sw6106mon
@@ -5,13 +5,21 @@
 
 start() {
   printf "Starting sw6106mon: "
-  /usr/local/bin/sw6106mon &
-	echo "OK" 
+  /usr/bin/sw6106mon &
+  if [ $? -ne 0 ]; then
+    echo "FAIL"
+    exit 1
+  fi
+
+  echo "OK"
 }
+
 stop() {
   printf "Stopping sw6106mon: "
-	killall sw6106mon
+  killall sw6106mon
+  echo "OK"
 }
+
 restart() {
   stop
   start
